# Generated by Django 4.2.16 on 2026-06-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("last_refreshed", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "course cache",
                "verbose_name_plural": "course caches",
                "db_table": "ilias_coursecache",
                "ordering": ["title"],
                "unique_together": {("user", "course_id")},
            },
        ),
    ]
