# Generated by Django 4.2.16 on 2026-06-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iliascredential",
            name="phpsessid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iliascredential",
            name="shibsession",
            field=models.TextField(blank=True, null=True),
        ),
    ]
